/* generated by vibec — do not edit; edit the .vibe source */
#include "vibert.h"

static const VbInfo vb_info_tuple = {"tuple", 0, 0};
static const VbInfo vbi_BadParse = {"BadParse", 0, 0};
static const VbInfo vbi_DivZero = {"DivZero", 0, 0};
static const VbInfo vbi_Er = {"Er", 1, 0};
static const VbInfo vbi_None = {"None", 0, 0};
static const VbInfo vbi_Ok = {"Ok", 1, 0};
static const VbInfo vbi_OutOfBounds = {"OutOfBounds", 0, 0};
static const VbInfo vbi_Overflow = {"Overflow", 0, 0};
static const VbInfo vbi_Some = {"Some", 1, 0};

static VbVal vbf_work(VbVal *a);
static VbVal vbf_spin(VbVal *a);
static VbVal vbf_main(VbVal *a);

#line 5 "churn"
static VbVal vbf_work(VbVal *a) {
  (void)a;
  VbMark vbm = vb_mark();
  VbVal v_n_1 = a[0];
  VbVal vbret = vb_unit();
  for (;;) {
    VbVal t2 = vb_range(vb_int(0), v_n_1);
    VbVal t3 = vb_rev(t2);
    vb_dispose(t2);
    VbVal t4 = t3;
    VbVal t5 = vb_len(t4);
    vb_dispose(t4);
    vbret = t5;
    break;
  }
  vb_release(vbm, vbret);
  return vbret;
}

#line 7 "churn"
static VbVal vbf_spin(VbVal *a) {
  (void)a;
  VbMark vbm = vb_mark();
  VbVal v_k_6 = a[0];
  VbVal v_acc_7 = a[1];
  VbVal vbret = vb_unit();
  for (;;) {
    #line 8 "churn"
    VbVal t8 = v_k_6;
    if (vb_eq(t8, vb_int(0))) {
      vbret = v_acc_7;
      break;
    }
    else if (1) {
      VbVal v___9 = t8;
      VbVal t10_a[] = {vb_int(5000)};
      VbVal t10 = vbf_work(t10_a);
      VbVal t11 = vb_sub(v_k_6, vb_int(1));
      VbVal t12 = vb_add(v_acc_7, t10);
      v_k_6 = t11;
      v_acc_7 = t12;
      continue;
    }
    else { vb_fail("Churn.spin.match", "no match arm applied"); }
  }
  vb_release(vbm, vbret);
  return vbret;
}

#line 13 "churn"
static VbVal vbf_main(VbVal *a) {
  (void)a;
  VbMark vbm = vb_mark();
  VbVal vbret = vb_unit();
  for (;;) {
    VbVal t13_a[] = {vb_int(2000), vb_int(0)};
    VbVal t13 = vbf_spin(t13_a);
    VbVal t14 = t13;
    VbVal t15 = vb_show(t14);
    vb_dispose(t14);
    VbVal t16 = t15;
    VbVal t17 = vb_out(t16);
    vb_dispose(t16);
    vbret = t17;
    break;
  }
  vb_release(vbm, vbret);
  return vbret;
}


int main(int argc, char **argv) {
  vb_init();
  vb_set_args(argc, argv);
  vbf_main(0);
  return 0;
}
