/* generated by vibec — do not edit; edit the .vibe source */
#include "vibert.h"

static const VbInfo vb_info_tuple = {"tuple", 0, 0};
static const VbInfo vbi_BadParse = {"BadParse", 0, 0};
static const VbInfo vbi_DivZero = {"DivZero", 0, 0};
static const VbInfo vbi_Er = {"Er", 1, 0};
static const VbInfo vbi_None = {"None", 0, 0};
static const VbInfo vbi_Ok = {"Ok", 1, 0};
static const VbInfo vbi_OutOfBounds = {"OutOfBounds", 0, 0};
static const VbInfo vbi_Overflow = {"Overflow", 0, 0};
static const VbInfo vbi_Some = {"Some", 1, 0};

static VbVal vbf_work(VbVal *a);
static VbVal vbf_spin(VbVal *a);
static VbVal vbf_main(VbVal *a);

#line 5 "churn"
static VbVal vbf_work(VbVal *a) {
  (void)a;
  VbMark vbm = vb_mark();
  VbVal v_n_1 = a[0];
  VbVal vbret = vb_unit();
  for (;;) {
    vbret = vb_len(vb_rev(vb_range(vb_int(0), v_n_1)));
    break;
  }
  vb_release(vbm, vbret);
  return vbret;
}

#line 7 "churn"
static VbVal vbf_spin(VbVal *a) {
  (void)a;
  VbMark vbm = vb_mark();
  VbVal v_k_2 = a[0];
  VbVal v_acc_3 = a[1];
  VbVal vbret = vb_unit();
  for (;;) {
    #line 8 "churn"
    VbVal t4 = v_k_2;
    if (vb_eq(t4, vb_int(0))) {
      vbret = v_acc_3;
      break;
    }
    else if (1) {
      VbVal v___5 = t4;
      VbVal t6_a[] = {vb_int(5000)};
      VbVal t6 = vbf_work(t6_a);
      VbVal t7 = vb_sub(v_k_2, vb_int(1));
      VbVal t8 = vb_add(v_acc_3, t6);
      v_k_2 = t7;
      v_acc_3 = t8;
      continue;
    }
    else { vb_fail("Churn.spin.match", "no match arm applied"); }
  }
  vb_release(vbm, vbret);
  return vbret;
}

#line 13 "churn"
static VbVal vbf_main(VbVal *a) {
  (void)a;
  VbMark vbm = vb_mark();
  VbVal vbret = vb_unit();
  for (;;) {
    VbVal t9_a[] = {vb_int(2000), vb_int(0)};
    VbVal t9 = vbf_spin(t9_a);
    vbret = vb_out(vb_show(t9));
    break;
  }
  vb_release(vbm, vbret);
  return vbret;
}


int main(int argc, char **argv) {
  vb_init();
  vb_set_args(argc, argv);
  vbf_main(0);
  return 0;
}
