/* generated by vibec — do not edit; edit the .vibe source */
#include "vibert.h"

static const VbInfo vb_info_tuple = {"tuple", 0, 0};
static const VbInfo vbi_BadParse = {"BadParse", 0, 0};
static const VbInfo vbi_DivZero = {"DivZero", 0, 0};
static const VbInfo vbi_Er = {"Er", 1, 0};
static const VbInfo vbi_None = {"None", 0, 0};
static const VbInfo vbi_Ok = {"Ok", 1, 0};
static const VbInfo vbi_OutOfBounds = {"OutOfBounds", 0, 0};
static const VbInfo vbi_Overflow = {"Overflow", 0, 0};
static const VbInfo vbi_Some = {"Some", 1, 0};

static VbVal vbf_main(VbVal *a);

#line 3 "hello"
static VbVal vbf_main(VbVal *a) {
  (void)a;
  VbMark vbm = vb_mark();
  VbVal vbret = vb_unit();
  for (;;) {
    VbVal t1 = vb_strz("hello from vibelang\n");
    VbVal t2 = vb_out(t1);
    vb_dispose(t1);
    vbret = t2;
    break;
  }
  vb_release(vbm, vbret);
  return vbret;
}


int main(int argc, char **argv) {
  vb_init();
  vb_set_args(argc, argv);
  vbf_main(0);
  return 0;
}
