/* generated by vibec — do not edit; edit the .vibe source */
#include "vibert.h"
#include <stdio.h>

static const VbInfo vb_info_tuple = {"tuple", 0, 0};
static const char *const vbfl_Ledger_Tx[] = {"sku", "qty", "price"};
static const VbInfo vbi_Ledger_Tx = {"Ledger.Tx", 3, vbfl_Ledger_Tx};
static const VbInfo vbi_BadParse = {"BadParse", 0, 0};
static const VbInfo vbi_DivZero = {"DivZero", 0, 0};
static const VbInfo vbi_Er = {"Er", 1, 0};
static const VbInfo vbi_Ledger_Bad = {"Ledger.Bad", 1, 0};
static const VbInfo vbi_Ledger_Num = {"Ledger.Num", 1, 0};
static const VbInfo vbi_Ledger_Void = {"Ledger.Void", 0, 0};
static const VbInfo vbi_None = {"None", 0, 0};
static const VbInfo vbi_Ok = {"Ok", 1, 0};
static const VbInfo vbi_OutOfBounds = {"OutOfBounds", 0, 0};
static const VbInfo vbi_Overflow = {"Overflow", 0, 0};
static const VbInfo vbi_Some = {"Some", 1, 0};

static VbVal vbf_Ledger_parse(VbVal *a);
static VbVal vbf_Ledger_mk(VbVal *a);
static VbVal vbf_Ledger_amt(VbVal *a);
static VbVal vbf_Ledger_total(VbVal *a);
static VbVal vbf_Ledger_mean(VbVal *a);
static VbVal vbf_Ledger_top(VbVal *a);
static VbVal vbf_Ledger_load(VbVal *a);
static VbVal vbf_Ledger_main(VbVal *a);

#line 10 "ledger"
static VbVal vbf_Ledger_parse(VbVal *a) {
  (void)a;
  VbVal v_ln_1 = a[0];
  VbVal vbret = vb_unit();
  for (;;) {
    #line 11 "ledger"
    VbVal t2 = vb_split(vb_char(44), v_ln_1);
    if (vb_as_vec(t2)->n == 3) {
      VbVal v_s_3 = vb_as_vec(t2)->a[0];
      VbVal v_q_4 = vb_as_vec(t2)->a[1];
      VbVal v_p_5 = vb_as_vec(t2)->a[2];
      #line 12 "ledger"
      VbVal t6 = vb_obj(&vb_info_tuple, 0, 2, vb_parse_int(v_q_4, 0, 32), vb_parse_f64(v_p_5));
      if (vb_tag(vb_field(t6, 0)) == 0 && vb_tag(vb_field(t6, 1)) == 0) {
        VbVal v_n_7 = vb_field(vb_field(t6, 0), 0);
        VbVal v_v_8 = vb_field(vb_field(t6, 1), 0);
        VbVal t9_a[] = {vb_dup(v_s_3), v_n_7, v_v_8};
        VbVal t9 = vbf_Ledger_mk(t9_a);
        vbret = t9;
        break;
      }
      else if (1) {
        VbVal v___10 = t6;
        vbret = vb_obj(&vbi_Er, 1, 1, vb_obj(&vbi_Ledger_Num, 1, 1, vb_dup(v_ln_1)));
        break;
      }
      else { vb_fail("Ledger.parse.match", "no match arm applied"); }
    }
    else if (1) {
      VbVal v___11 = t2;
      vbret = vb_obj(&vbi_Er, 1, 1, vb_obj(&vbi_Ledger_Bad, 0, 1, vb_dup(v_ln_1)));
      break;
    }
    else { vb_fail("Ledger.parse.match", "no match arm applied"); }
  }
  return vbret;
}

#line 19 "ledger"
static VbVal vbf_Ledger_mk(VbVal *a) {
  (void)a;
  VbVal v_s_12 = a[0];
  VbVal v_n_13 = a[1];
  VbVal v_v_14 = a[2];
  VbVal vbret = vb_unit();
  for (;;) {
    #line 20 "ledger"
    VbVal t15 = vb_bool(false);
    if (vb_as_bool(vb_bool(vb_cmp(v_n_13, vb_int(0)) > 0))) {
      t15 = vb_bool(vb_cmp(v_v_14, vb_float(0.0)) > 0);
    }
    VbVal t16 = t15;
    if (vb_eq(t16, vb_bool(true))) {
      VbVal t17 = vb_obj(&vbi_Ledger_Tx, 0, 3, v_s_12, v_n_13, v_v_14);
      {
        VbVal v_sku_18 = vb_field(t17, 0);
        VbVal v_qty_19 = vb_field(t17, 1);
        VbVal v_price_20 = vb_field(t17, 2);
        vb_require(vb_as_bool(vb_bool(vb_cmp(v_qty_19, vb_int(0)) > 0)), "Ledger.Tx.invariant", "qty > 0");
        vb_require(vb_as_bool(vb_bool(vb_cmp(v_price_20, vb_float(0.0)) > 0)), "Ledger.Tx.invariant", "price > 0");
      }
      vbret = vb_obj(&vbi_Ok, 0, 1, t17);
      break;
    }
    else if (vb_eq(t16, vb_bool(false))) {
      vbret = vb_obj(&vbi_Er, 1, 1, vb_obj(&vbi_Ledger_Bad, 0, 1, v_s_12));
      break;
    }
    else { vb_fail("Ledger.mk.match", "no match arm applied"); }
  }
  return vbret;
}

#line 25 "ledger"
static VbVal vbf_Ledger_amt(VbVal *a) {
  (void)a;
  VbVal v_t_21 = a[0];
  VbVal vbret = vb_unit();
  for (;;) {
    vbret = vb_mul(vb_field(v_t_21, 2), vb_to_f64(vb_field(v_t_21, 1)));
    break;
  }
  return vbret;
}

#line 26 "ledger"
static VbVal vbf_Ledger_total(VbVal *a) {
  (void)a;
  VbVal v_ts_22 = a[0];
  VbVal vbret = vb_unit();
  for (;;) {
    VbVal t23 = vb_clos(vbf_Ledger_amt, "Ledger.amt", 1);
    VbVal t24 = vb_map(t23, v_ts_22);
    vb_dispose(t23);
    vbret = vb_sum(t24);
    break;
  }
  return vbret;
}

#line 28 "ledger"
static VbVal vbf_Ledger_mean(VbVal *a) {
  (void)a;
  VbVal v_ts_25 = a[0];
  vb_require(vb_as_bool(vb_bool(vb_cmp(vb_len(v_ts_25), vb_int(0)) > 0)), "Ledger.mean.pre", "len ts > 0");
  VbVal vbret = vb_unit();
  for (;;) {
    VbVal t26_a[] = {v_ts_25};
    VbVal t26 = vbf_Ledger_total(t26_a);
    vbret = vb_div(t26, vb_to_f64(vb_len(v_ts_25)), "Ledger.mean.div");
    break;
  }
  return vbret;
}

#line 29 "ledger"
static VbVal vbf_Ledger_top(VbVal *a) {
  (void)a;
  VbVal v_ts_27 = a[0];
  vb_require(vb_as_bool(vb_bool(vb_cmp(vb_len(v_ts_27), vb_int(0)) > 0)), "Ledger.top.pre", "len ts > 0");
  VbVal vbret = vb_unit();
  for (;;) {
    VbVal t28 = vb_clos(vbf_Ledger_amt, "Ledger.amt", 1);
    VbVal t29 = vb_max_by(t28, v_ts_27, "Ledger.top.max_by");
    vb_dispose(t28);
    vbret = vb_dup(t29);
    break;
  }
  return vbret;
}

#line 31 "ledger"
static VbVal vbf_Ledger_load(VbVal *a) {
  (void)a;
  VbVal v_p_30 = a[0];
  VbVal vbret = vb_unit();
  for (;;) {
    #line 32 "ledger"
    VbVal v_txt_31 = vb_read(v_p_30);
    #line 33 "ledger"
    VbVal t32 = vb_clos(vbf_Ledger_parse, "Ledger.parse", 1);
    VbVal t33 = vb_lines(v_txt_31);
    VbVal t34 = vb_map(t32, t33);
    vb_dispose(t32);
    vb_dispose(t33);
    VbVal t35 = vb_seq(t34);
    if (vb_tag(t35) == 1) {
      VbVal v_e_36 = vb_field(t35, 0);
      VbVal t37 = vb_obj(&vbi_Er, 1, 1, v_e_36);
      vb_dispose(v_txt_31);
      vbret = t37;
      break;
    }
    else if (vb_tag(t35) == 0 && vb_as_vec(vb_field(t35, 0))->n == 0) {
      VbVal t38 = vb_obj(&vbi_Er, 1, 1, vb_obj(&vbi_Ledger_Void, 2, 0));
      vb_dispose(v_txt_31);
      vbret = t38;
      break;
    }
    else if (vb_tag(t35) == 0) {
      VbVal v_ts_39 = vb_field(t35, 0);
      VbVal t40 = vb_obj(&vbi_Ok, 0, 1, v_ts_39);
      vb_dispose(v_txt_31);
      vbret = t40;
      break;
    }
    else { vb_fail("Ledger.load.match", "no match arm applied"); }
  }
  return vbret;
}

#line 39 "ledger"
static VbVal vbf_Ledger_main(VbVal *a) {
  (void)a;
  VbVal vbret = vb_unit();
  for (;;) {
    #line 40 "ledger"
    VbVal t41 = vb_strz("ledger.csv");
    VbVal t42_a[] = {t41};
    VbVal t42 = vbf_Ledger_load(t42_a);
    vb_dispose(t41);
    VbVal v_r_43 = t42;
    #line 41 "ledger"
    VbVal t44 = v_r_43;
    if (vb_tag(t44) == 1) {
      VbVal v_e_45 = vb_field(t44, 0);
      VbVal t46 = vb_show(v_e_45);
      VbVal t47 = vb_warn(t46);
      vb_dispose(t46);
      vb_dispose(v_r_43);
      vbret = t47;
      break;
    }
    else if (vb_tag(t44) == 0) {
      VbVal v_ts_48 = vb_field(t44, 0);
      VbVal t49 = vb_strz("n={} tot={} avg={} top={}");
      VbVal t50 = vb_len(v_ts_48);
      VbVal t51_a[] = {v_ts_48};
      VbVal t51 = vbf_Ledger_total(t51_a);
      VbVal t52 = t51;
      VbVal t53_a[] = {v_ts_48};
      VbVal t53 = vbf_Ledger_mean(t53_a);
      VbVal t54 = t53;
      VbVal t55_a[] = {v_ts_48};
      VbVal t55 = vbf_Ledger_top(t55_a);
      VbVal t56 = vb_fmt(t49, 4, t50, t52, t54, vb_field(t55, 0));
      vb_dispose(t49);
      vb_dispose(t50);
      vb_dispose(t52);
      vb_dispose(t54);
      VbVal t57 = t56;
      VbVal t58 = vb_out(t57);
      vb_dispose(t57);
      vb_dispose(v_r_43);
      vbret = t58;
      break;
    }
    else { vb_fail("Ledger.main.match", "no match arm applied"); }
  }
  return vbret;
}


/* exp c — C ABI surface (spec §10.2) */
double Ledger_mean(VbVal x0) {
  vb_init();
  VbVal a[1];
  a[0] = x0;
  VbVal r = vbf_Ledger_mean(a);
  return (double)vb_as_float(r);
}
double Ledger_total(VbVal x0) {
  vb_init();
  VbVal a[1];
  a[0] = x0;
  VbVal r = vbf_Ledger_total(a);
  return (double)vb_as_float(r);
}

int main(int argc, char **argv) {
  vb_init();
  vb_set_args(argc, argv);
  vbf_Ledger_main(0);
  return 0;
}
