/* generated by vibec — do not edit; edit the .vibe source */
#include "vibert.h"
#include <stdio.h>

static const VbInfo vb_info_tuple = {"tuple", 0, 0};
static const char *const vbfl_Tx[] = {"sku", "qty", "price"};
static const VbInfo vbi_Tx = {"Tx", 3, vbfl_Tx};
static const VbInfo vbi_Bad = {"Bad", 1, 0};
static const VbInfo vbi_BadParse = {"BadParse", 0, 0};
static const VbInfo vbi_DivZero = {"DivZero", 0, 0};
static const VbInfo vbi_Er = {"Er", 1, 0};
static const VbInfo vbi_None = {"None", 0, 0};
static const VbInfo vbi_Num = {"Num", 1, 0};
static const VbInfo vbi_Ok = {"Ok", 1, 0};
static const VbInfo vbi_OutOfBounds = {"OutOfBounds", 0, 0};
static const VbInfo vbi_Overflow = {"Overflow", 0, 0};
static const VbInfo vbi_Some = {"Some", 1, 0};
static const VbInfo vbi_Void = {"Void", 0, 0};

static VbVal vbf_parse(VbVal *a);
static VbVal vbf_mk(VbVal *a);
static VbVal vbf_amt(VbVal *a);
static VbVal vbf_total(VbVal *a);
static VbVal vbf_mean(VbVal *a);
static VbVal vbf_top(VbVal *a);
static VbVal vbf_load(VbVal *a);
static VbVal vbf_main(VbVal *a);

static VbVal vbw_Bad(VbVal *a) { (void)a; return vb_obj(&vbi_Bad, 0, 1, a[0]); }
static VbVal vbw_Er(VbVal *a) { (void)a; return vb_obj(&vbi_Er, 1, 1, a[0]); }
static VbVal vbw_Num(VbVal *a) { (void)a; return vb_obj(&vbi_Num, 1, 1, a[0]); }
static VbVal vbw_Ok(VbVal *a) { (void)a; return vb_obj(&vbi_Ok, 0, 1, a[0]); }

#line 10 "ledger"
static VbVal vbf_parse(VbVal *a) {
  (void)a;
  VbMark vbm = vb_mark();
  VbVal v_ln_1 = a[0];
  VbVal vbret = vb_unit();
  for (;;) {
    #line 11 "ledger"
    VbVal t2 = vb_split(vb_char(44), v_ln_1);
    if (vb_as_vec(t2)->n == 3) {
      VbVal v_s_3 = vb_as_vec(t2)->a[0];
      VbVal v_q_4 = vb_as_vec(t2)->a[1];
      VbVal v_p_5 = vb_as_vec(t2)->a[2];
      #line 12 "ledger"
      VbVal t6 = vb_obj(&vb_info_tuple, 0, 2, vb_parse_int(v_q_4, 0), vb_parse_f64(v_p_5));
      if (vb_tag(vb_field(t6, 0)) == 0 && vb_tag(vb_field(t6, 1)) == 0) {
        VbVal v_n_7 = vb_field(vb_field(t6, 0), 0);
        VbVal v_v_8 = vb_field(vb_field(t6, 1), 0);
        VbVal t9_a[] = {vb_dup(v_s_3), v_n_7, v_v_8};
        VbVal t9 = vbf_mk(t9_a);
        vbret = t9;
        break;
      }
      else if (1) {
        VbVal v___10 = t6;
        VbVal t11 = vb_apply1(vb_clos(vbw_Num, "Num", 1), vb_dup(v_ln_1));
        VbVal t12 = vb_apply1(vb_clos(vbw_Er, "Er", 1), t11);
        vbret = t12;
        break;
      }
      else { vb_fail("Ledger.parse.match", "no match arm applied"); }
    }
    else if (1) {
      VbVal v___13 = t2;
      VbVal t14 = vb_apply1(vb_clos(vbw_Bad, "Bad", 1), vb_dup(v_ln_1));
      VbVal t15 = vb_apply1(vb_clos(vbw_Er, "Er", 1), t14);
      vbret = t15;
      break;
    }
    else { vb_fail("Ledger.parse.match", "no match arm applied"); }
  }
  vb_release(vbm, vbret);
  return vbret;
}

#line 19 "ledger"
static VbVal vbf_mk(VbVal *a) {
  (void)a;
  VbMark vbm = vb_mark();
  VbVal v_s_16 = a[0];
  VbVal v_n_17 = a[1];
  VbVal v_v_18 = a[2];
  VbVal vbret = vb_unit();
  for (;;) {
    #line 20 "ledger"
    VbVal t19 = vb_bool(false);
    if (vb_as_bool(vb_bool(vb_cmp(v_n_17, vb_int(0)) > 0))) {
      t19 = vb_bool(vb_cmp(v_v_18, vb_float(0.0)) > 0);
    }
    VbVal t20 = t19;
    if (vb_eq(t20, vb_bool(true))) {
      VbVal t21 = vb_obj(&vbi_Tx, 0, 3, v_s_16, v_n_17, v_v_18);
      {
        VbVal v_sku_22 = vb_field(t21, 0);
        VbVal v_qty_23 = vb_field(t21, 1);
        VbVal v_price_24 = vb_field(t21, 2);
        vb_require(vb_as_bool(vb_bool(vb_cmp(v_qty_23, vb_int(0)) > 0)), "Tx.invariant", "qty > 0");
        vb_require(vb_as_bool(vb_bool(vb_cmp(v_price_24, vb_float(0.0)) > 0)), "Tx.invariant", "price > 0");
      }
      VbVal t25 = vb_apply1(vb_clos(vbw_Ok, "Ok", 1), t21);
      vbret = t25;
      break;
    }
    else if (vb_eq(t20, vb_bool(false))) {
      VbVal t26 = vb_apply1(vb_clos(vbw_Bad, "Bad", 1), v_s_16);
      VbVal t27 = vb_apply1(vb_clos(vbw_Er, "Er", 1), t26);
      vbret = t27;
      break;
    }
    else { vb_fail("Ledger.mk.match", "no match arm applied"); }
  }
  vb_release(vbm, vbret);
  return vbret;
}

#line 25 "ledger"
static VbVal vbf_amt(VbVal *a) {
  (void)a;
  VbMark vbm = vb_mark();
  VbVal v_t_28 = a[0];
  VbVal vbret = vb_unit();
  for (;;) {
    vbret = vb_mul(vb_field(v_t_28, 2), vb_to_f64(vb_field(v_t_28, 1)));
    break;
  }
  vb_release(vbm, vbret);
  return vbret;
}

#line 26 "ledger"
static VbVal vbf_total(VbVal *a) {
  (void)a;
  VbMark vbm = vb_mark();
  VbVal v_ts_29 = a[0];
  VbVal vbret = vb_unit();
  for (;;) {
    vbret = vb_sum(vb_map(vb_clos(vbf_amt, "amt", 1), v_ts_29));
    break;
  }
  vb_release(vbm, vbret);
  return vbret;
}

#line 28 "ledger"
static VbVal vbf_mean(VbVal *a) {
  (void)a;
  VbMark vbm = vb_mark();
  VbVal v_ts_30 = a[0];
  vb_require(vb_as_bool(vb_bool(vb_cmp(vb_len(v_ts_30), vb_int(0)) > 0)), "Ledger.mean.pre", "len ts > 0");
  VbVal vbret = vb_unit();
  for (;;) {
    VbVal t31_a[] = {v_ts_30};
    VbVal t31 = vbf_total(t31_a);
    vbret = vb_div(t31, vb_to_f64(vb_len(v_ts_30)), "Ledger.mean.div");
    break;
  }
  vb_release(vbm, vbret);
  return vbret;
}

#line 29 "ledger"
static VbVal vbf_top(VbVal *a) {
  (void)a;
  VbMark vbm = vb_mark();
  VbVal v_ts_32 = a[0];
  vb_require(vb_as_bool(vb_bool(vb_cmp(vb_len(v_ts_32), vb_int(0)) > 0)), "Ledger.top.pre", "len ts > 0");
  VbVal vbret = vb_unit();
  for (;;) {
    vbret = vb_max_by(vb_clos(vbf_amt, "amt", 1), v_ts_32, "Ledger.top.max_by");
    break;
  }
  vb_release(vbm, vbret);
  return vbret;
}

#line 31 "ledger"
static VbVal vbf_load(VbVal *a) {
  (void)a;
  VbMark vbm = vb_mark();
  VbVal v_p_33 = a[0];
  VbVal vbret = vb_unit();
  for (;;) {
    #line 32 "ledger"
    VbVal v_txt_34 = vb_read(v_p_33);
    #line 33 "ledger"
    VbVal t35 = vb_seq(vb_map(vb_clos(vbf_parse, "parse", 1), vb_lines(v_txt_34)));
    if (vb_tag(t35) == 1) {
      VbVal v_e_36 = vb_field(t35, 0);
      VbVal t37 = vb_apply1(vb_clos(vbw_Er, "Er", 1), v_e_36);
      vbret = t37;
      break;
    }
    else if (vb_tag(t35) == 0 && vb_as_vec(vb_field(t35, 0))->n == 0) {
      VbVal t38 = vb_apply1(vb_clos(vbw_Er, "Er", 1), vb_obj(&vbi_Void, 2, 0));
      vbret = t38;
      break;
    }
    else if (vb_tag(t35) == 0) {
      VbVal v_ts_39 = vb_field(t35, 0);
      VbVal t40 = vb_apply1(vb_clos(vbw_Ok, "Ok", 1), v_ts_39);
      vbret = t40;
      break;
    }
    else { vb_fail("Ledger.load.match", "no match arm applied"); }
  }
  vb_release(vbm, vbret);
  return vbret;
}

#line 39 "ledger"
static VbVal vbf_main(VbVal *a) {
  (void)a;
  VbMark vbm = vb_mark();
  VbVal vbret = vb_unit();
  for (;;) {
    #line 40 "ledger"
    VbVal t41_a[] = {vb_strz("ledger.csv")};
    VbVal t41 = vbf_load(t41_a);
    VbVal v_r_42 = t41;
    #line 41 "ledger"
    VbVal t43 = v_r_42;
    if (vb_tag(t43) == 1) {
      VbVal v_e_44 = vb_field(t43, 0);
      vbret = vb_warn(vb_show(v_e_44));
      break;
    }
    else if (vb_tag(t43) == 0) {
      VbVal v_ts_45 = vb_field(t43, 0);
      VbVal t46_a[] = {v_ts_45};
      VbVal t46 = vbf_total(t46_a);
      VbVal t47_a[] = {v_ts_45};
      VbVal t47 = vbf_mean(t47_a);
      VbVal t48_a[] = {v_ts_45};
      VbVal t48 = vbf_top(t48_a);
      vbret = vb_out(vb_fmt(vb_strz("n={} tot={} avg={} top={}"), 4, vb_len(v_ts_45), t46, t47, vb_field(t48, 0)));
      break;
    }
    else { vb_fail("Ledger.main.match", "no match arm applied"); }
  }
  vb_release(vbm, vbret);
  return vbret;
}


/* exp c — C ABI surface (spec §10.2) */
double Ledger_mean(VbVal x0) {
  vb_init();
  VbVal a[1];
  a[0] = x0;
  VbVal r = vbf_mean(a);
  return (double)vb_as_float(r);
}
double Ledger_total(VbVal x0) {
  vb_init();
  VbVal a[1];
  a[0] = x0;
  VbVal r = vbf_total(a);
  return (double)vb_as_float(r);
}

int main(int argc, char **argv) {
  vb_init();
  vb_set_args(argc, argv);
  vbf_main(0);
  return 0;
}
